---
swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: "/"
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: hello-controller
  description: Hello Controller
paths:
  "/heure":
    get:
      tags:
      - hello-controller
      summary: hello
      operationId: helloUsingGET
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Heure"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Heure:
    type: object
    properties:
      heure:
        type: integer
        format: int32
      minute:
        type: integer
        format: int32
    title: Heure
 

