/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Heure from '../model/Heure';

/**
* HelloController service.
* @module api/HelloControllerApi
* @version 1.0
*/
export default class HelloControllerApi {

    /**
    * Constructs a new HelloControllerApi. 
    * @alias module:api/HelloControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the helloUsingGET operation.
     * @callback module:api/HelloControllerApi~helloUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Heure} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * hello
     * @param {module:api/HelloControllerApi~helloUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Heure}
     */
    helloUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Heure;
      return this.apiClient.callApi(
        '/heure', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
