/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp2.introspection;

import org.junit.Test;
import tp2.JoueurGolf;
import tp2.WoodClub;
import tp2.injection.ApplicationContext;

import java.lang.reflect.InvocationTargetException;

import static org.junit.Assert.assertEquals;

public class AppTest {
    @Test
    public void testInjecteur() {
        ApplicationContext.register(IClub.class, WoodClub.class);
    }

    @Test
    public void testInjecteurCreation() throws InstantiationException, IllegalAccessException, IllegalArgumentException,
            InvocationTargetException, NoSuchMethodException, SecurityException {
        ApplicationContext.register(IClub.class, WoodClub.class);
        JoueurGolf golfeur = ApplicationContext.getBean(JoueurGolf.class);
        assertEquals(10, golfeur.poidClub(), 10e-5);
    }

    @Test
    public void testInjecteurMessageBoker() throws InstantiationException, IllegalAccessException,
            IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException {
        ApplicationContext.register(IClub.class, WoodClub.class);
        JoueurGolf golfeur = ApplicationContext.getBean(JoueurGolf.class);
        assertEquals(10, golfeur.poidClub(), 10e-5);

        golfeur.signaleClubTropLourd();
        assertEquals(5, golfeur.poidClub(), 10e-5);
    }
}
